/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddInvoiceForm: typeof import('./src/components/AddInvoiceForm.vue')['default']
    AddItemsForm: typeof import('./src/components/addItemsForm.vue')['default']
    AsiliNavBar: typeof import('./src/components/asiliNavBar.vue')['default']
    DashboardVendeur: typeof import('./src/components/DashboardVendeur.vue')['default']
    DashbordVendeur: typeof import('./src/components/dashbordVendeur.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateInvoiceForm: typeof import('./src/components/updateInvoiceForm.vue')['default']
    UpdateItemForm: typeof import('./src/components/updateItemForm.vue')['default']
  }
}
